# Site settings
title: Test Blog
description: "Blog"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

  # email: your-email@domain.com
# description: "Great site about Jekyll on GH-Pages."


# Build settings
remote_theme: jekyll/minima
