title: Test Blog
# author: 
  # name: Studious
 #  social_links: 
  twitter: studious_reader
  instagram: studiousraeder
  markdown: krandown
  theme: minima

# navigation:                
 # - {file: "index.md", title: "Home"}
 # - {file: "about.md", title: "About"}
  


